using System.Collections.Generic;

namespace Mivi.Core
{
    public struct MidiNote
    {
        public readonly int MidiIndex;
        public readonly string? Note;
        public readonly int Octave;

        public MidiNote(int midiIndex, string note, int octave)
        {
            MidiIndex = midiIndex;
            Note = note;
            Octave = octave;
        }

        public const int LowestPianoIndex = 21;
        public const int HighestPianoIndex = 108;

        public static readonly IReadOnlyList<MidiNote> Notes = new[]
        {
            new MidiNote(0, "C", -2),
            new MidiNote(1, "C#", -2),
            new MidiNote(2, "D", -2),
            new MidiNote(3, "D#", -2),
            new MidiNote(4, "E", -2),
            new MidiNote(5, "F", -2),
            new MidiNote(6, "F#", -2),
            new MidiNote(7, "G", -2),
            new MidiNote(8, "G#", -2),
            new MidiNote(9, "A", -2),
            new MidiNote(10, "A#", -2),
            new MidiNote(11, "B", -2),
            new MidiNote(12, "C", -1),
            new MidiNote(13, "C#", -1),
            new MidiNote(14, "D", -1),
            new MidiNote(15, "D#", -1),
            new MidiNote(16, "E", -1),
            new MidiNote(17, "F", -1),
            new MidiNote(18, "F#", -1),
            new MidiNote(19, "G", -1),
            new MidiNote(20, "G#", -1),
            new MidiNote(21, "A", -1),
            new MidiNote(22, "A#", -1),
            new MidiNote(23, "B", -1),
            new MidiNote(24, "C", 0),
            new MidiNote(25, "C#", 0),
            new MidiNote(26, "D", 0),
            new MidiNote(27, "D#", 0),
            new MidiNote(28, "E", 0),
            new MidiNote(29, "F", 0),
            new MidiNote(30, "F#", 0),
            new MidiNote(31, "G", 0),
            new MidiNote(32, "G#", 0),
            new MidiNote(33, "A", 0),
            new MidiNote(34, "A#", 0),
            new MidiNote(35, "B", 0),
            new MidiNote(36, "C", 1),
            new MidiNote(37, "C#", 1),
            new MidiNote(38, "D", 1),
            new MidiNote(39, "D#", 1),
            new MidiNote(40, "E", 1),
            new MidiNote(41, "F", 1),
            new MidiNote(42, "F#", 1),
            new MidiNote(43, "G", 1),
            new MidiNote(44, "G#", 1),
            new MidiNote(45, "A", 1),
            new MidiNote(46, "A#", 1),
            new MidiNote(47, "B", 1),
            new MidiNote(48, "C", 2),
            new MidiNote(49, "C#", 2),
            new MidiNote(50, "D", 2),
            new MidiNote(51, "D#", 2),
            new MidiNote(52, "E", 2),
            new MidiNote(53, "F", 2),
            new MidiNote(54, "F#", 2),
            new MidiNote(55, "G", 2),
            new MidiNote(56, "G#", 2),
            new MidiNote(57, "A", 2),
            new MidiNote(58, "A#", 2),
            new MidiNote(59, "B", 2),
            new MidiNote(60, "C", 3),
            new MidiNote(61, "C#", 3),
            new MidiNote(62, "D", 3),
            new MidiNote(63, "D#", 3),
            new MidiNote(64, "E", 3),
            new MidiNote(65, "F", 3),
            new MidiNote(66, "F#", 3),
            new MidiNote(67, "G", 3),
            new MidiNote(68, "G#", 3),
            new MidiNote(69, "A", 3),
            new MidiNote(70, "A#", 3),
            new MidiNote(71, "B", 3),
            new MidiNote(72, "C", 4),
            new MidiNote(73, "C#", 4),
            new MidiNote(74, "D", 4),
            new MidiNote(75, "D#", 4),
            new MidiNote(76, "E", 4),
            new MidiNote(77, "F", 4),
            new MidiNote(78, "F#", 4),
            new MidiNote(79, "G", 4),
            new MidiNote(80, "G#", 4),
            new MidiNote(81, "A", 4),
            new MidiNote(82, "A#", 4),
            new MidiNote(83, "B", 4),
            new MidiNote(84, "C", 5),
            new MidiNote(85, "C#", 5),
            new MidiNote(86, "D", 5),
            new MidiNote(87, "D#", 5),
            new MidiNote(88, "E", 5),
            new MidiNote(89, "F", 5),
            new MidiNote(90, "F#", 5),
            new MidiNote(91, "G", 5),
            new MidiNote(92, "G#", 5),
            new MidiNote(93, "A", 5),
            new MidiNote(94, "A#", 5),
            new MidiNote(95, "B", 5),
            new MidiNote(96, "C", 6),
            new MidiNote(97, "C#", 6),
            new MidiNote(98, "D", 6),
            new MidiNote(99, "D#", 6),
            new MidiNote(100, "E", 6),
            new MidiNote(101, "F", 6),
            new MidiNote(102, "F#", 6),
            new MidiNote(103, "G", 6),
            new MidiNote(104, "G#", 6),
            new MidiNote(105, "A", 6),
            new MidiNote(106, "A#", 6),
            new MidiNote(107, "B", 6),
            new MidiNote(108, "C", 7),
            new MidiNote(109, "C#", 7),
            new MidiNote(110, "D", 7),
            new MidiNote(111, "D#", 7),
            new MidiNote(112, "E", 7),
            new MidiNote(113, "F", 7),
            new MidiNote(114, "F#", 7),
            new MidiNote(115, "G", 7),
            new MidiNote(116, "G#", 7),
            new MidiNote(117, "A", 7),
            new MidiNote(118, "A#", 7),
            new MidiNote(119, "B", 7),
            new MidiNote(120, "C", 8),
            new MidiNote(121, "C#", 8),
            new MidiNote(122, "D", 8),
            new MidiNote(123, "D#", 8),
            new MidiNote(124, "E", 8),
            new MidiNote(125, "F", 8),
            new MidiNote(126, "F#", 8),
            new MidiNote(127, "G", 8)
        };
    }
}
